### ISSUE TITLE
Speed up instruction search

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#105]
ATM the first few characters in the search take a lot of time, subsequent runs are much faster, I assume it is because as the data is filtered down the search has to run on fewer entries and becomes faster.

Possible solutions:

- debounce user input to reduce the number of filtering operations
- add a loader
- try to use a library (maybe what is used by the rust or python docs) that can produce a reverse index to speed up the search

**Comment by bobbinth** [comment]
@hackaugusto - was this intended for the [examples](https://github.com/0xPolygonMiden/examples) repo?

**Comment by hackaugusto** [comment]
oops, it was, sorry about that!
