### ISSUE TITLE
Always show the search input on the instructions table

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#106]
ATM the search input is only visible when the page is scrolled all the way to the top, if the users don't pay attention they may not realize that search is available, and users that know of the search feature have to scroll all the way back to the top to use it.

A solution is to add the search input along side the table's header, which is sticky and always visible.

**Comment by bobbinth** [comment]
@hackaugusto - was this intended for the [examples](https://github.com/0xPolygonMiden/examples) repo?
