### ISSUE TITLE
`MerkleStore` API uses `Word` instead of `Digest`

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#131]
The `MerkleStore` API uses `Word` instead of `Digest` for all of it's public methods (`with_merkle_tree` / `with_sparse_merkle_tree` / `get_node` etc).  All merkle objects in the `MerkleStore` are natively of type `Digest` i.e. they are the digest of a hashing permutation - this is inclusive of leaves, inner nodes and the root.  Should the API be updated such that it expects arguments of type `Digest` instead of `Word` or is there some reason behind using `Word`?

**Comment by hackaugusto** [comment]
related discussion: https://github.com/0xPolygonMiden/crypto/pull/121#discussion_r1156237319

**Comment by vlopes11** [comment]
Related issue: https://github.com/0xPolygonMiden/crypto/issues/59

**Comment by bobbinth** [comment]
Closed by #157.
