### ISSUE TITLE
Implement `MerkleStore::{with_tiered_smt, add_tiered_smt}`

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/crypto#135]
Following the same pattern to add leaves of other algorithms into the `MerkleStore`, we should introduce the following methods:

```rust
MerkeStore::with_tiered_smt<R, I>(
    mut self,
    entries: R
) -> Result<Self, MerkleError>
where
    R: IntoIterator<IntoIter = I>,
    I: Iterator<Item = (Word, Word)>
```

```rust
MerkeStore::add_tiered_smt<R, I>(
    &mut self,
    entries: R
) -> Result<Word, MerkleError>
where
    R: IntoIterator<IntoIter = I>,
    I: Iterator<Item = (Word, Word)>
```

`with_tiered_smt` will be a builder pattern, and `add_tiered_smt` will return the new root.

The inclusion should follow the implementation described in #22 

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-vm/pull/808#discussion_r1163674101_

**Comment by bobbinth** [comment]
Closed by #153.
