### ISSUE TITLE
`MerkleStore` extract structures

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#141]
`AccountStorage` is structured as follow:

```rust
pub struct AccountStorage {
    slots: SimpleSmt,   // SMT of depth 8
    store: MerkleStore, // Merkle store for any tree data
}
```

The leaves of the `SimpleSmt` can represent roots of Merkle structures stored in the `MerkleStore`.  For more information on this implementation see [here](https://github.com/0xPolygonMiden/miden-base/issues/92). To support such an implementation we need the ability to extract Merkle structures from the `MerkleStore` based on their roots.  The interface we would need to implement is:

```Rust
impl MerkleStore {
    pub fn subtree(&self, root: Word) -> MerkleStore
}
```

Or maybe even:

```Rust
impl MerkleStore {
    pub fn subset(&self, roots: &[Word]) -> MerkleStore
}
```

**Comment by bobbinth** [comment]
Closed by #151.
