### ISSUE TITLE
`SimpleSmt.get_node(..)` infallible branch

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#143]
When fetching a leaf from a `SimpleSmt` the lookup should be infallible. Hence we should replace `ok_or(...)` with `expect(..)` in the code below.

https://github.com/0xPolygonMiden/crypto/blob/52db23cd423e01a92eaf92abfd25aeef5b882c92/src/merkle/simple_smt/mod.rs#L132-L135

**Comment by bobbinth** [comment]
Closed by #149.
