### ISSUE TITLE
`SimpleSmt` implement `leaves` `Iterator`

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#150]
We need to be able to populate the `advice_map` with entries for account procedure hash -> method leaf index such that the VM can fetch the index for a particular account procedure hash from the `AdviceProvider`.  The VM can use the leaf index to authenticate the account procedure hash against the account code root. 

To achieve this I propose we implement a method on `SimpleSmt` that provides an iterator over `leaves`.  This iterator would have `Item = (u64, Word)` (index, leaf).

**Comment by bobbinth** [comment]
Closed by #151.
