### ISSUE TITLE
Return node depth with `upper_leaves()` return for `TieredSmt`

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#155]
To populate the `AdviceMap` with `TieredSmt` leaves we need to compute the "remaining key". To compute the remaining key we need to know the depth of the upper leaf. To support this computation we should modify the `upper_leaves()` method to include the leaf depth.

We have a requirement for this in `miden-base` where we [populate the `AdviceMap`](https://github.com/0xPolygonMiden/miden-base/blob/a8e39271150ac6af7cb2eb7d9f798b98490e61f5/objects/src/accounts/mod.rs#LL161C1-L167C11) with the leafs associated with the account `AssetVault`:

```rust
        // populate advice map with tiered merkle tree leaf nodes
        self.vault.asset_tree().upper_leaves().for_each(|(node, key, value)| {
            // TODO: temporary hack - assume the node is interted at depth 16 and compute remaining key accordingly
            let mut key = Word::from(key);
            key[3] = ((key[3].as_int() << 16) >> 16).into();
            target.insert_into_map(*node, key.into_iter().chain(value).collect());
        })
```

**Comment by bobbinth** [comment]
I believe this has been closed by #173 and related PRs. But if not, we can re-open this issue.
