### ISSUE TITLE
Investigate SVE acceleration for RPO hash function

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/crypto#158]
Rounds of [RPO hash function](https://github.com/0xPolygonMiden/crypto/blob/main/src/hash/rpo/mod.rs) have a very regular structure which should be amenable to vectorized computation. This is especially true for the [inverse alpha](https://github.com/0xPolygonMiden/crypto/blob/main/src/hash/rpo/mod.rs#L414) portion which applies ~70 identical operations to a state of 12 elements. This portion is by far the most time-consuming part of the hash function.

By using vectorized instructions, it may be possible to speed the hash function up by 2x - 3x (though, this needs to be confirmed). As one of our target machines for Miden VM is Graviton 3, which supports SVE extension, it would be great to see if can get this type of speed up there.

Ideally, we'd want to add a feature to this crate which, when enabled, would replace the current pure Rust code for either the entire RPO [permutation](https://github.com/0xPolygonMiden/crypto/blob/main/src/hash/rpo/mod.rs#L414), a single RPO [round](https://github.com/0xPolygonMiden/crypto/blob/main/src/hash/rpo/mod.rs#L345), are even just the [inverse alpha](https://github.com/0xPolygonMiden/crypto/blob/main/src/hash/rpo/mod.rs#L345) computation.

**Comment by hackaugusto** [comment]
have we also looked at hashing in the GPU? It could be useful in the VM to not compute the hash of the control blocks in the CPU while producing a trace, but compute the hash of all the blocks at the end using the GPU instead.

**Comment by bobbinth** [comment]
Yes, hashing on GPUs is something that we've actually already implemented on Apple silicon ([see here](https://github.com/0xPolygonMiden/miden-vm/blob/next/prover/src/gpu.rs)). However it is done for a different step: during proof generation rather than during trace construction.

For trace construction, going all the way to the GPU might be an overkill (number of hashes we need to compute there is relatively small). But I think it would be very beneficial to offload hash computations for trace construction to other threads (right now, the whole trace generation process runs in a single thread, and I suspect we can speed it up a lot by parallelizing things like hashing).

**Comment by bobbinth** [comment]
Closed by #190.
