### ISSUE TITLE
Hashing the full key instead of remainder key in TSMT

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/crypto#159]
The way we currently compute the values of leaves in the TSMT is as `Hash(rem_key || value; domain=depth)` for depths less than $64$ and as `Hash((rem_key_1, value_1) || ... || (rem_key_n, value_n); domain=64)` for depth $64$.
The use of both `rem_key` and `domain=depth` is an overkill as knowing the full key and the depth yields the remainder key.
Thus, we can either hash the full key instead of the remainder key or hash the remainder key and let `domain=1` to domain separate leaf nodes from internal nodes.

**Comment by Al-Kindi-0** [comment]
I can't see why it shouldn't work. As long as we always check that the prefix of length `depth` of the full key is the index in the compact tree, then both constructions are equivalent.

**Comment by frisitano** [comment]
related: #155

**Comment by bobbinth** [comment]
Closed by #173.
