### ISSUE TITLE
Add `EMPTY_VALUE` associated constant to `TieredSmt` 

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#160]
The `TieredSmt` acts as a key value map.  In cases when there is no value set against a specific key the `TieredSmt` will return an "empty word" - that is a word composed of `ZERO`s. We should introduce an associated type on the `TieredSmt` that represents this empty word.  We can name this `EMTPY_VALUE` or `EMPTY_WORD`.  I would vote on the former as it has more contextual meaning in the context of the `TieredSmt` key value map.

See [here](https://github.com/0xPolygonMiden/miden-base/pull/128#discussion_r1214630294) for initial discussion and motivation.

**Comment by bobbinth** [comment]
Closed by #161.
