### ISSUE TITLE
`MerkleStore` Merkle tree leaf iterator

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#172]
As part of #171 we introduced a method `non_empty_leaves(..)` on the `MerkleStore` which provides an iterator over leaves of a Merkle tree with the specified root and depth.  However the current implementation is not suitable for iterating over the leaves of a tiered SMT.  We should refactor the implementation such that it works for tiered SMT's as well.  See [this](https://github.com/0xPolygonMiden/crypto/pull/171#discussion_r1274715172) comment for proposed changes.

**Comment by bobbinth** [comment]
@frisitano is this closed by #189?

**Comment by frisitano** [comment]
> @frisitano is this closed by #189?

yes it is.
