### ISSUE TITLE
Rename `TieredSmt::with_leaves(..)` to `TieredSmt::with_entries(..)`

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/crypto#188]
If I understand correctly the `TieredSmt::with_leaves(..)` takes an iterator of `(key, value)` pairs.  It then in turn inserts these pairs into the tree. The values provided as argument are not leaves but instead they are the values (pre-images) of the leaves stored in the tree.  As such maybe it would be more appropriate to rename the method `with_entries(..)` or `with_values(..)` to better reflect the methods semantics.

**Comment by bobbinth** [comment]
Yes, agreed that the naming is somewhat misleading. Personally, I would prefer `with_entries()`.

**Comment by bobbinth** [comment]
Closed by #192.
