### ISSUE TITLE
Investigate AVX512 acceleration for RPO hash function

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/crypto#198]
Many Intel and latest AMD CPUs support AVX512 instructions. One example of these are AWS C7a instances. While these are more expensive than Graviton 3 instances ($3.3 vs. $2.3 per hour for a 64-core instance), if we can get ~3x improvement in RPO performance by utilizing AVX512 instruction set, these instances will be cost-competitive with the Graviton instances.

So, it would be good to do something similar as was done in #190 but for AVX512 instruction set.

**Comment by Dominik1999** [comment]
Do we want as baseline RPO on Miden VM v0.6 or v0.7?

**Comment by bobbinth** [comment]
Closed by #234.
