### ISSUE TITLE
Migrate simple Sparse Merkle tree

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/crypto#21]
We have an implementation of a simple SMT in the main Miden repo [here](https://github.com/maticnetwork/miden/blob/main/core/src/inputs/advice/sparse_merkle_tree.rs). We should migrate this implementation to this crate, probably under `src/merkle/simple_smt.rs`.

We can improve the implementation and documentation during the migration process, but I would spend too much time on this.

**Comment by vlopes11** [comment]
Closed by https://github.com/0xPolygonMiden/crypto/pull/27
