### ISSUE TITLE
`merkle` module: remove obsolete structures

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/crypto#248]
We may be able to get rid of this whole file. Previously, it was used in `miden-base`, but after https://github.com/0xPolygonMiden/miden-base/pull/409, we might not need it any more. Let's create an issue for this.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/crypto/pull/245#discussion_r1449457464_

I think `TryApplyDiff` is another one of these obsolete things which we can probably remove. Let's add this to the issue I mentioned in the previous comment.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/crypto/pull/245#discussion_r1449491708_

**Comment by bobbinth** [comment]
Closed by #257.
