### ISSUE TITLE
`Smt`: Add methods

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/crypto#250]
We should add the following methods to `Smt`:

- `get_value(&self, key: RpoDigest) -> Word`.
- Something similar to `Tsmt::prove()`.
- `inner_nodes(&self) -> impl Iterator<Item = InnerNodeInfo>`.
- `leaves(&self) -> impl Iterator<Item = (u64, &SmtLeaf)>`.
- `entries(&self) -> impl Iterator<Item = &(RpoDigest, Word)>`.

From https://github.com/0xPolygonMiden/crypto/pull/245#pullrequestreview-1822565310

**Comment by bobbinth** [comment]
Closed by #268.
