### ISSUE TITLE
Update hash functions security estimates

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/crypto#259]
We should either update the security estimate of our (algebraic) hash functions or add an argument for the current one.

**Comment by Al-Kindi-0** [comment]
Given the proof in the last paragraph of Appendix C in the updated version of the [xHash paper](https://eprint.iacr.org/2023/1045.pdf) the following can be closed.

**Comment by Al-Kindi-0** [comment]
I can make a small PR with an explicit reference.

**Comment by bobbinth** [comment]
Closed by #320.
