### ISSUE TITLE
Deserialization: Entire signature should be sent in instead of the slice

### ISSUE THREAD

**Issue by bulenttastan** [0xPolygonMiden/crypto#265]
https://github.com/0xPolygonMiden/crypto/blob/c86bdc6d515046513a86ec331da5a0f77fd29cf2/src/dsa/rpo_falcon512/signature.rs#L128

The signature is already sliced with `[41..]` inside polynomial.rs, this input should just be `&sig` instead.

**Comment by bobbinth** [comment]
Closed by #266. Thank you again for flagging this!
