### ISSUE TITLE
Reproducible Build

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#282]
- [ ] use `cargo make`
- [ ] add `Cargo.lock` to repo
- [ ] add `rust-toolchain.toml`
- [ ] update ci to use `cargo make` rules
- [ ] update CONTRIBUTING.md to mention `cargo make`
- [ ] update `pre-commmit.yaml` to use `cargo make`

ref: https://github.com/0xPolygonMiden/miden-vm/issues/1259

**Comment by bobbinth** [comment]
Closed by #296.
