### ISSUE TITLE
Panic during MMR verification

### ISSUE THREAD

**Issue by PhilippGackstatter** [0xPolygonMiden/crypto#332]
This issue describes two scenarios which are similar in which verification on an `Mmr` can panic. This seems undesirable given that verification might be done on a node and panicking could open the node to a denial of service attack. Instead `verify` should never panic and always return a proper verification outcome.

Depending on whether we will continue to use `Mmr`s or not, this issue will be relevant or not.

## Validating user input

Setting the position and forest on a proof in such a way that they return a `peak_index()` greater than what the current mmr has will panic. This could presumably happen since proofs would be deserialized from arbitrary user input.
This test should suceed (the proof should be invalid), but it panics instead:

```rust
#[test]
fn test_mmr_panic() {
    let mmr: Mmr = LEAVES[0..4].iter().cloned().into();
    let mut proof = mmr.open(3, mmr.forest()).unwrap();
    proof.forest = 5;
    proof.position = 4;
    assert!(!mmr.peaks(mmr.forest).unwrap().verify(LEAVES[3], proof));
}
```

### Verifying an older proof

The same can happen when verifying an older proof against a newer version. When the proof is created here, the number of peaks is 2, but when adding a leaf, the number of peaks reduces since trees are merged and thus the older proof verified against the newer MMR version will panic:

```rust
#[test]
fn test_mmr_panic() {
    let leaves_len = 3;
    let mut mmr = Mmr::from(LEAVES[0..leaves_len].iter().cloned());

    let leaf_idx = leaves_len - 1;
    let proof = mmr.open(leaf_idx, mmr.forest()).unwrap();
    assert!(mmr.peaks(mmr.forest()).unwrap().verify(LEAVES[leaf_idx], proof.clone()));

    mmr.add(LEAVES[leaves_len]);
    mmr.peaks(mmr.forest()).unwrap().verify(LEAVES[leaf_idx], proof);
}
```

Both of these are due to unconditional indexing into the peaks, which should be made fallible instead and the error handled.

https://github.com/0xPolygonMiden/crypto/blob/876d1bf97aad45100fd725304569a62f0103d13b/src/merkle/mmr/peaks.rs#L86-L89

### Improve user experience

Although a separate topic, this refactor could be used to let `verify` return an error instead of a `bool` which is better for DevX since the error can describe why the proof failed to verify, while a bool is very coarse and therefore unhelpful for debugging.

**Comment by Fumuran** [comment]
Closed by #335.
