### ISSUE TITLE
Add `Smt::is_empty`

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [0xPolygonMiden/crypto#333]
I've needed to assert that a tree is empty in tests a few times.

From what I understand, a current method to achieve this is comparing the root against the appropriate pre-generated [empty roots](https://github.com/0xPolygonMiden/crypto/blob/dbab0e9aa9477cda8151fa3ff226dc4fb339aff9/src/merkle/empty_roots.rs#L30). One just needs to know the correct depth of the tree.

It would be easier (and more discoverable) if the SMT had an `is_empty` method, which I presume could just `self.leaves.len() > 0`.

In some cases comparing the root would still be preferable so I wonder if this couldn't be added as an associated constant `EMPTY_ROOT` - though I'm unsure if it would allow a compile time lookup to the empty roots or not.

Or maybe I've just missed something; I'm not very familiar with this crate :)

**Comment by bobbinth** [comment]
Good idea! We should definitely add the `is_empty()` method.

`EMPTY_ROOT` constant would be great too - but agreed that unclear if we can do it.

**Comment by bobbinth** [comment]
Closed by #337.
