### ISSUE TITLE
Implement tiered compact sparse Merkle tree

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/crypto#36]
The following issue aims at implementing the idea of a tiered sparse Merkle tree as proposed by @bobbinth in #22. The aim of such an implementation is to get a gauge of the out-of-VM performance and complexity so that these could be compared with their counterparts for the VM. 
Operations at depths greater than 64 can for the time being use the idea of a sorted list as explained [here](https://github.com/0xPolygonMiden/crypto/issues/22#issuecomment-1369563556). In the future we might use a more robust solution if the latter proves frail in some realistic scenarios.

**Comment by bobbinth** [comment]
Closed by #152 and others.
