### ISSUE TITLE
Implement compact sparse Merkle tree in Miden assembly

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/crypto#37]
The following issue aims at implementing the idea of a tiered sparse Merkle tree as proposed by @bobbinth in #22 in Miden assembly. The aim of such an implementation is to get a gauge of the performance and complexity of such an approach so that bottlenecks are identified and new VM instructions and decorators are introduced if needed.

**Comment by bobbinth** [comment]
Closed by https://github.com/0xPolygonMiden/miden-vm/pull/1046, https://github.com/0xPolygonMiden/miden-vm/issues/1048, https://github.com/0xPolygonMiden/miden-vm/pull/1036 and other related PRs.
