### ISSUE TITLE
Integrate sparse Merkle tree in advice provider

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/crypto#38]
After the implementation of #36 and during that of #37, integrating the proposed implementation of a compact SMT in the advice provided is the logical next step. This issue aims at tracking this step.

**Comment by Al-Kindi-0** [comment]
To make use of the tiered-SMT we have designed thus far, we need to integrate it within the current advice provider interface we have at the moment.


This is complicated due to the following reasons:
1.  The current implementation of `MerkleSet` works as a map from a `root` to a (binary) tree with nodes indexed by `NodeIndex` struct i.e. `(index, depth)`. On the other hand, the tiered-SMT is a key-value map which maps a `Word` to a `Word` (I am overlooking the case of ordered list to keep things simple for now).
2. Since a tiered-SMT is a compact SMT, the concept of depth doesn't make sense without a context. The context is defined by the key in question as well as the operation we are carrying at the time. This is in contrast with the current `MerkleSet` implementation where `depth` is fixed once and for all.
3. With the goal of making manipulations involving tiered-SMT efficient we need to make use of the cryptographic Miden assembly instructions that exist e.g. `mtree_set`. These instructions take as input only Merkle roots as well as `(index, depth)`. This again should be contrasted with manipulations on a key-value map like the tiered-SMT.

In order to solve the above, we can use a stateful variant of `MerkleSet`, call it `TieredSMT`. This would have, for example a `pre_insert` method which reads a key-value pair from the stack as well as the root of the tree we want to insert into, and then probes the tree to figure out:
1. The type of insertion i.e. simple or complex.
2. The `(index, depth)` to be used with `mtree_set`. In the case of a complex insertion, an appropriate `(index, depth)` of the sibling with a common prefix is also provided so that it can be inserted at a deeper level.
3. The necessary flags that should be provided ND. In the case of simple insertion, these are the flags to decide between `insert16`, `insert32`... . In the case of complex insertion the flags are used to decide on the length of the common prefix.
Using the above, the MASM code for doing insertion would work as follows:
1.  Upon calling `exec.insert` on a stack in the following configuration `[K, V, R, ...]`, an advice decorator named `adv.pre_insert_tiered_smt` will be executed. This will fetch the tiered-SMT with root `R` and provide the necessary data needed to accomplish the insertion based on the state of the tree as well as `[K, V]`. It will also update the state of the tiered-SMT with root `R` so that it maps `[K, V]` to an `(index, depth)` so that when a call to `mtree_set` is later performed, the storage of the tiered-SMT is updated by adding `[K, V]`.
2. Based on the provided flags, either a complex or simple insertion will be performed. This will also update the state of the tiered-SMT `MerkleSet` so that the map from key-value pairs to `NodeIndex` is updated to remove `[K, V]`.
3. Throughout the above, a decorator called `adv.set_smt_depth` will need to be called to change the depth of the tiered-SMT especially during a complex insertion.
To make the above work, we will need to add the ability of inserting at any `NodeIndex` regardless of whether or not the resulting configuration is legal. More precisely, when doing a complex insertion we have the following sequence of actions we need to perform:
1. Find the pre-existing leaf node, with a given` (index, depth) = (i, d)` sharing a long common prefix with the new node we want to insert.
2.  Insert an empty root at `(i, d)`.
3. Find the new `(index, depth)` where we need to insert the pre-existing node, call it `(i_0, d_0)`.
4. Insert the preexisitng node at `(i_0, d_0)`. This were we need the new ability.
5. Conclude by finding the `(index, depth)`, call it `(i_1, d_1)` where we will insert the new leaf node (the one that initiated point 1). Note that `d_0 == d_1`.
I have made an attempt at implementing the above [here](https://github.com/0xPolygonMiden/miden-vm/pull/724). The only thing missing is the capability to perform point 4 above during a complex insertion.

**Comment by bobbinth** [comment]
Closed by https://github.com/0xPolygonMiden/miden-vm/pull/1046, https://github.com/0xPolygonMiden/miden-vm/issues/1048, https://github.com/0xPolygonMiden/miden-vm/pull/1036 and other related PRs.
