### ISSUE TITLE
MerklePathSet is using irregular path

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/crypto#57]
The `MerklePath` structure assumes the input node is an argument of the verification

https://github.com/0xPolygonMiden/crypto/blob/6bd6b9e7ceda0af8892eac2cd8b73783dcbda27d/src/merkle/path.rs#L25-L39

But `MerklePathSet` injects the input node as the first element of the path

https://github.com/0xPolygonMiden/crypto/blob/66da469ec49a7a4a72631a8b553ba3470d0173fa/src/merkle/merkle_path_set.rs#L33-L64

And, when queried, it will remove it

https://github.com/0xPolygonMiden/crypto/blob/66da469ec49a7a4a72631a8b553ba3470d0173fa/src/merkle/merkle_path_set.rs#L118-L119

It should probably store the path only with the siblings, having a different strategy to store the leaf node, if required

After this refactor is done, `MerklePathSet` should consume the `MerklePath` functions to compute roots and verify openings.

https://github.com/0xPolygonMiden/crypto/pull/53#discussion_r1104479230

**Comment by bobbinth** [comment]
This is kind of intended behavior since each path actually stores both leaves.
