### ISSUE TITLE
Add BLAKE3 hash function

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/crypto#6]
We should add wrappers for BLAKE3 hash function into `hash` module. These could be similar to the ones implemented in [Winterfell](https://github.com/novifinancial/winterfell/blob/main/crypto/src/hash/blake/mod.rs#L19). In terms of variants, would be great to have the following:

* `Blake3_256` - same as in Winterfell.
* `Blake3_192` - same as in Winterfell.
* `Blake3_160` - a version of BLAKE3 with output truncated to 20 bytes.

**Comment by vlopes11** [comment]
To clarify; since they already implement `Hasher`, should we just re export [Blake3_192](https://docs.rs/winter-crypto/0.4.2/winter_crypto/hashers/struct.Blake3_192.html) from winter crypto?

**Comment by bobbinth** [comment]
We could re-export both `Blake3_256` and `Blake_192` from `winter-crypto`, but I'd prefer to just copy the code here (it's not a lot of code). This way, all 3 implementations are in the same place, and we avoid the risk of them diverging later on.

**Comment by bobbinth** [comment]
Closed by #14
