### ISSUE TITLE
Set correct collision resistance for Rpo256

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/crypto#69]
We are currently defining the collision resistance of Rpo256 as a constant for the type.

However, this will not always be true, as we might drop it to 126-bits, depending on the capacity registers setup.

Ideally, we should split the `Rpo256` into two distinct types, and set the collision attribute/capacity setup strategies individually. This way, we would   create a better distinction and unmistakable representation of what we should expect from the implementation.

We should evaluate the options we have available and solve the comment below.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/crypto/pull/68#discussion_r1112177713_

**Comment by bobbinth** [comment]
Closed by #236.
