### ISSUE TITLE
Efficient tree implementations for the mtree_cwm instruction

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#81]
The instruction `mtree_cwm` is defined as:

> Copies a Merkle tree with root R and updates a node at depth d and index i in the copied tree to value V′.

We currently have the following tree implementations:

- Sparse Merkle Tree
- Merkle Mountain Range
- Simple Merkle Tree

For all the data structures above, depending on the size of the tree a copy is potentially a very expensive operation. The issue is about how to design the above structure as so to support a more efficient `mtree_cwm`

**Comment by hackaugusto** [comment]
The semantics of `mtree_cwm` implies in both a new copy, and a change to this copy. The issue at the hand is the cost of the copy itself. To remove it we can use copy-on-write, or use a persistent data structure.

**Comment by grjte** [comment]
This issue may be superseded by the discussion of the `AdviceProvider` changes (https://github.com/0xPolygonMiden/miden-vm/discussions/750) and the proposed replacement of `mtree_cwm` by `mtree_clone` (https://github.com/0xPolygonMiden/miden-vm/issues/762). Wdyt?
