### ISSUE TITLE
Efficient lazy loading of tree data for VM execution

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#83]
The VM supports a `mtree_get` operation. This operation references a tree by its root. For the VM to work with the tree's data (for queries / updates / copies), the VM has to load the data into memory. This could be optimized to only load the necessary data in memory.

Open questions are: At which point will this be a good strategy? (code complexity vs. performance gains)

**Comment by bobbinth** [comment]
> For the VM to work with the tree's data (for queries / updates / copies), the VM has to load the data into memory.

I think this is only true for the [MemAdviceProvider](https://github.com/0xPolygonMiden/miden-vm/blob/main/processor/src/advice/mem_provider.rs). We can implement an advice provider which does lazy loading (and I think we'll have to sooner rather than later).
