### ISSUE TITLE
Support deleting leaves on existing Tree implementations

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#85]
Tree types that should support delete:

- Sparse Merkle Tree

These two won't support deleted:

- Simple Merkle Tree
- Merkle Mountain Range

**Comment by hackaugusto** [comment]
The easiest of the bunch is SMT, since the delete can be implemented in terms of an insert, and moving elements up. The other 2 trees would have very high cost to delete an element. AFAIU the delete operation will be limited to SMT, is that correct?

**Comment by bobbinth** [comment]
Yeah - I agree that we should avoid deletions as much as possible. I don't think we need to support them explicitly for most data structures - but we do need to have something like this for the compact STM (i.e., our version of it - tiered SMT). But even there, I think we can handle a deletion via updating on internal node.

**Comment by hackaugusto** [comment]
this is no longer necessary: the merkle store is being used as a generic backend, and it is possible to set leaf / internal nodes with that implementation.
