### ISSUE TITLE
Compact representation for persistent structures

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/crypto#90]
This is a proposal on how to represent multiple versions of the supported data structures efficiently in memory and disk.

Properties of this proposal:

- It should be possible to move forward and backwards in a tree's history efficiently [rationale](https://github.com/0xPolygonMiden/crypto/issues/22#issuecomment-1410991001)
- Data is laid out sequentially
  - easy to index the data
  - fast to send the data over network
  - fast to load the structure in memory 
- The representation should be compact enough as to not become prohibitively for thousands of versions of the tree, both in terms of required disk and memory space
  - The disk use case is the same for the rationale on the link above
  - The memory use case is to support copy-on-write in the advice provider in the Miden VM

On any Merkle structure, the contents of a internal node depends on the contents of the leaves, this proposal assumes there is no additional data in any of the internal nodes, i.e the leaves alone are sufficient to reconstruct the structures.

The idea is to maintain a log of the changes to the leaves. This could be as simple as:

```rust
#[repr(transparent)]
struct Append {
  el: Word,
}

struct Log {
  Vec<Append>
}
```

The above representation is optimal w.r.t storage, since only the data that can't be recomputed is stored. It is a great representation for archive nodes and for a warp sync style protocol.

### First optimization

Caching: With the above when a tree is required, it would need to be reconstructed from the log, this would be very wasteful for the most important case, using the last version of the tree. A solution is to have snapshots of the tree managed in a caching strategy, a proposed strategy is `latest` version + `LRU` cache of size $n$ of requested versions + `snapshots` every $2^n$ steps.

### Extending the log

The log proposed above is only for append operations, this is useful for structures like MMR, but it is not so useful for a tiered sparse merkle tree, that structure supports deletion, which is internally implemented as setting a specific leaf back to the zero value. This opens first design point

1. Should there be a generic log available for all structures? Or a log tailored for each?

I'm going to assume the later, the idea is that a tailored log would permit better optimizations to exist, for example, the log above uses a transparent operation, whereas the following representation for a tiered sparse merkle tree needs extra space for the tagged union.

Second log:

```rust
enum Op {
  Insert{leaf: Word}, // alternatively would be (key, value)
  Delete{pos: usize},
}

struct Op {
  Vec<Append>
}
```

### Second optimization

Moving backwards: The caching above would be limited in size, for example, we could implement a LRU cache with 2 entries in addition to the latest version. If these entries are for versions `[1024,  2048]` but the structure receives a request for version `1000`, without the ability to move backwards in time a new structure starting from `0` would have to be constructed. If the version can go backwards then only `24` ops would have to be applied.

To achieve this, the insert operation would need to declare what it overwrote, e.g.:

```rust
enum Op {
  Insert{new: Word, old: Word},  // alternatively old: usize, this would require a full log
  Delete{pos: usize},
}

struct Op {
  Vec<Append>
}
```

When going **backwards** in the tiered sparse Merkle tree history, the `Insert` would mean replace the value in `new` with `old`.

### Lookups

The structure represented here uses version numbers to represent the data structure, this may be fine on some use cases, but for the advice provider in the VM the goal is to support `mtree_get`, which operates on the structure hash instead of its version number.

To support this we can add reverse maps:

```rust
BTreeMap<Word, usize>
```

Using this map we can lookup the corresponding tree. This proposal has the map outside of the operation log, the operation log stays more compact that way, and it allows for the map above to have fewer entries if necessary.

**Comment by hackaugusto** [comment]
The description above is useful for a single structure. The assumption is that in most cases we have a single structure associated with an entity, for example, an account would have a single state tree, single vault, a rollup would have a single MMR with the rollup blocks.

If we do need branching, as in, creating a new structure from an existing one, there are a few possibilities:

- Copy the old log to the new. This would be the most straight forward implementation and okay for small structures
- Create a fresh copy, discarding the original log.
     - This may be useful only for structures in which the log would be drastically larger than the number of leafs in the tree. So not super useful for a MMR.
- Create an operation in the log to represent `Fork`, and point to another structure.
     - In this case, I would make the cache shared among the structures, and the fork point would have optionally be a snapshot, just like the latest version of the structure
- If this operation would be heavily used, then @frisitano 's [proposal](https://github.com/0xPolygonMiden/crypto/issues/89#issuecomment-1460048151) of a single KV storage for all structures would be better

**Comment by frisitano** [comment]
This look interesting.  I'll need to take some time to fully digest the implications.  One concern / comment is around the need for branching. I think this will be a very common operation so we want this to be as efficient as possible.

**Comment by vlopes11** [comment]
> On any Merkle structure, the contents of a internal node depends on the contents of the leaves, this proposal assumes there is no additional data in any of the internal nodes, i.e the leaves alone are sufficient to reconstruct the structures.

Preliminary, we need to keep in mind that the tiered sparse merkle tree will have leaves in arbitrary depth. This is ofc not a matter of semantics, but depending on how the assumptions are defined, we might have leaves as node, as the maximum depth of the tiered sparse merkle tree will be 64, but we will have leaf data at 16, 32, 48, 64.

**Comment by hackaugusto** [comment]
> This look interesting. I'll need to take some time to fully digest the implications. One concern / comment is around the need for branching. I think this will be a very common operation so we want this to be as efficient as possible.

I have two questions:

- I don't see how this would be a common operation, could you exemplify?
- This shouldn't be an issue if with the proposal above, even for branching out of large structures. I'm actually more worried about merging

> Preliminary, we need to keep in mind that the tiered sparse merkle tree will have leaves in arbitrary depth. 

This shouldn't be an issue for this proposal. This does not propose to serialize the data structure in disk, but the operation that resulted in the structure, so for example, in real code we do something like:

```rust
let mut smt = SMT::new();
smt.add(v1);
smt.add(v2_that_collides);
```

In the example above `v1` starts at one level, and it is pushed to another level by the conflict on `v2`, and it works fine because `add` handles that. The proposal here is basically to encode the operation `add` and the value of that operation in a log. When reading the log the same code that produces correct behavior is called, which will automatically behave as expected.

**Comment by bobbinth** [comment]
Closing this as we will be using sqlite for persistent storage (at least for now).
