### ISSUE TITLE
Tiered sparse merkle tree requirements

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/crypto#91]
# Miden VM - TSMT

## Definition

A tiered sparse merkle tree will be a compound of sparse merkle trees combined into tiers. It will map 256-bits keys to 256-bits values, and will extend the functionality of sparse merkle trees.

Keys and values are arrays of 64-bits field elements `F`. We will use the last limb of the key to represent our `traversing key`.

- `T`: Depth per tier, set to `16`.
- `M`: Maximum number of tiers, set to `4`.
- `D`: Maximum depth of the tree, set to `T ⋅ M = 64`
- `H({F}) -> F`: Hash primitive of choice
- `H_{t}({F}) -> F`: Hash in domain `t`, where the maximum `t = D = 64`
- `H_0(depth) -> F`: Set of empty sub-tree constants for a target depth.

#### Lookup

Requirements:

- `H_0(depth) -> F`
- `H_{t}({F}) -> F`
- `Node(state, depth, index) -> Node Value: F`
- `Traverse(state, bits) -> Target Node Depth Index: (F, F)`
- `Traverse Key(Key, B) -> Bits: F`

For a `state` of the tree (i.e. root), given a key, it will lookup its structure and find the appropriate node for that key. This will be referenced as `target node` within this document.

`Lookup(Root, Key, Value) -> (Depth, Index)`

For the first tier, we will:

- Compute `bits := Traverse Key(Key, B)` for `B = T = 16`

Traverse key will get the most significant bits `B` from the `traversing key` of `Key`.

- Compute the node value for that tier: `V := H_{B}(Key, Value)`
- Fetch the `target node` via a traverse function `(depth, index) := Traverse(state, bits)`

The tree traversal is straightforward as it will be the same as a regular sparse merkle tree. For the sake of simplicity, we use below a `T = 4` and a 8-bits key `0b10010110`.

![image](https://user-images.githubusercontent.com/8730839/223483098-4b63741a-514a-408f-9ee5-2d5047fcdc11.png)

We start from the orange root, traverse the green nodes in accordance to the most significant bits of the key, and finish at the purple target node. The index pair for that tree will be `(depth = 4, index = 9)`.

- Fetch a node value `N := Node(state, depth, index)`
- If the node value `N` equals `V` or `H_0(depth)`, returns `(depth, index)`. Otherwise, continue traversing until the next tier.

For the second tier `t = 2`, we will:

- Compute `bits := Traverse Key(Key, B)` for `B = t ⋅ T = 2 ⋅ 16 = 32`
- Compute the node value for that tier: `N := H_{B}(Key, Value)`
- Fetch the `target node` via a traverse function `(depth, index) := Traverse(state, bits)`
- Fetch a node value `V := Node(state, depth, index)`
- If the node value `N` equals `V`, returns `(depth, index)`. If `V = H_0(depth)`, returns `(depth, index)` of the previous iteration.

Otherwise, continue traversing until `B = 64`. If we reach the maximum `depth = D = 64`, returns `(64, index)`, where `index` is the traversed value for that maximum depth.

#### Node value for the last tier

Requirements:

- `Order Leaves By Key({(Key, Value)}) -> {(Key, Value})`

The last tier might contain multiple leaves per node. We introduce a `Node Value Last Tier(leaves: {Key, Value}) -> F` procedure to compute the node values, and will behave as follows

- Order `leaves` via `ordered leaves := Order Leaves By Key(leaves)`
- Return the hash in domain for the max depth `D = 64` as `Node Value Last Tier(ordered leaves: {Key, Value}) -> H_64(ordered leaves)`

#### Membership proof

Requirements:

- `H_{t}({F}) -> F`
- `Last Tier Leaves(index) -> {(Key, Value)}`
- `Lookup(Root, Key, Value) -> (Depth, Index)`
- `Merkle Opening(Root, V, index, Merkle Path) -> boolean`
- `Merkle Path(Root, depth, index) -> Merkle Path`
- `Node(state, depth, index) -> Node Value: F`
- `Node Value Last Tier(leaves) -> F`

To check if a candidate leaf `(Key, Value)` opens to a state `Root`, we proceed as follows:

- Fetch the `target node` via `(depth, index) := Lookup(Root, Key, Value)`
- Compute the node value for that tier via `N := H_{depth}(Key, Value)`
- If the depth is `64`, fetch all leaves of the `target node` via `leaves := Last Tier Leaves(index)`, assert `(Key, Value)` belongs to `leaves`, and replace `N := Node Value Last Tier(leaves)`
- Fetch the node value of the state via `V := Node(Root, depth, index)`
- Fetch the merkle path for the `target node` via `P := Merkle Path(Root, depth, index)`
- Assert the correctness of the opening via `Merkle Opening(Root, V, index, P)`

Note: Both `Merkle Path` and `Merkle Opening` definitions doesn't belong to the scope of this document and are assumed to be known by the reader.

#### Non-Membership proof

Requirements:

- `Fetch Pre Image(Root, depth, index) -> {F}`
- `H_0(depth) -> F`
- `H_{t}({F}) -> F`
- `Last Tier Leaves(index) -> {(Key, Value)}`
- `Lookup(Root, Key, Value) -> (Depth, Index)`
- `Merkle Opening(Root, V, index, Merkle Path) -> boolean`
- `Merkle Path(Root, depth, index) -> Merkle Path`
- `Node(state, depth, index) -> Node Value: F`
- `Node Value Last Tier(leaves) -> F`

To check if a candidate leaf `(Key, Value)` doesn't exist for a state `Root`, we proceed as follows:

- Fetch the `target node` via `(depth, index) := Lookup(Root, Key, Value)`
- Fetch the node value via `N := Node(Root, depth, index)`
- Fetch the merkle path for the `target node` via `P := Merkle Path(Root, depth, index)`
- Assert the correctness of the opening via `Merkle Opening(Root, V, P)`

In order to prove non-membership, we need to open the pre-image of `target node` and assert it doesn't contain the candidate leaf. The proof that we know a pre-image that will compute the opening correctly will suffice to prove the non-membership.

- If `N = H_0(depth)`, then the proof holds.
- Otherwise, if `depth < D`, we fetch the pre-image `(Key', Value') := Fetch Pre Image(Root, depth, index)` and assert `N = H_{depth}(Key', Value') && Key != Key' && Value != Value'`. We can, alternatively, skip the value check as the key could independently verify the set membership - that would be up to the target use case.
- Finally, if `depth = D`, then we fetch `leaves := Last Tier Leaves(index)`, assert `(Key, Value)` doesn't exist in `leaves`, and assert `N = Node Value Last Tier(leaves)`.

#### Insert new leaf

Requirements:

- `Fetch Pre Image(Root, depth, index) -> {F}`
- `H_0(depth) -> F`
- `H_{t}({F}) -> F`
- `Insert Leaf(Root, N, depth, index, Key, Value) -> New Root: F`
- `Last Tier Leaves(index) -> {(Key, Value)}`
- `Lookup(Root, Key, Value) -> (Depth, Index)`
- `Node(state, depth, index) -> Node Value: F`
- `Node Value Last Tier(leaves) -> F`
- `Traverse(state, bits) -> Target Node Depth Index: (F, F)`
- `Traverse Key(Key, B) -> Bits: F`

The insertion of a leaf `(Key, Value)` for a state `Root` should be implemented as follows:

- Fetch the `target node` via `(depth, index) := Lookup(Root, Key, Value)`
- Compute the node value for that tier via `N := H_{depth}(Key, Value)`
- Fetch the node value of the state via `V := Node(Root, depth, index)`
- If `V = H_0(depth)`, then `Insert Leaf(Root, N, depth, index, Key, Value)`
- Otherwise, if `depth = D = 64`, then we fetch `leaves := Last Tier Leaves(index)`, append `(Key, Value)` to the set `leaves` (note that a set cannot hold duplicated values), compute the node value `N := Node Value Last Tier(leaves)`, and `Insert Leaf(Root, N, depth, index, Key, Value)`

Finally, if the previous cases aren't met, we have a collision. We should promote both leaves until they don't collide.

- Compute the depth of the next tier via `next tier depth := depth + T`
- Fetch the node pre-image of the sibling via `(Sibling Key, Sibling Value) := Fetch Pre Image(Root, depth, index)`
- Compute the sibling traversing bits via `sibling bits := Traverse Key(Sibling Key, next tier depth)`
- Fetch the `target sibling node` via the traverse function `(sibling new depth, sibling new index) := Traverse(state, sibling bits)`
- Compute the traversing bits via `bits := Traverse Key(Key, next tier depth)`
- Fetch the `target node` via the traverse function `(new depth, new index) := Traverse(state, bits)`

If `new depth = D = 64`, then we insert the sibling and leaf into their indexes using the previous method for the maximum depth.

Otherwise, if `new index != sibling new index`, it means we can insert the nodes back into the tree:

- Compute the sibling node value for that tier via `Sibling N := H_{new depth}(Sibling Key, Sibling Value)`, then `New Root := Insert Leaf(Root, Sibling N, new depth, sibling new index, Sibling Key, Sibling Value)`

Note that this command should override the previous leaf from the set. It means it should behave the same as if we entirely removed the sibling from the set, and inserted it into the new depth and index.

- Compute the value for that tier via `N := H_{new depth}(Key, Value)`, then `Insert Leaf(New Root, N, new depth, new index, Key, Value)`

Finally, if `new index = sibling new index`, we repeat the procedure, promoting the leaves to the next tier.

## MidenVM

The `Lookup` operation is used for all the routines. These are the requirements for its implementation.

- `H_0(depth) -> F`
- `H_{t}({F}) -> F`
- `Node(state, depth, index) -> Node Value: F`
- `Traverse(state, bits) -> Target Node Depth Index: (F, F)`
- `Traverse Key(Key, B) -> Bits: F`

The remainder operations will require:

- `Fetch Pre Image(Root, depth, index) -> {F}`
- `Insert Leaf(Root, N, depth, index, Key, Value) -> New Root: F`
- `Last Tier Leaves(index) -> {(Key, Value)}`
- `Merkle Opening(Root, V, index, Merkle Path) -> boolean`
- `Merkle Path(Root, depth, index) -> Merkle Path`
- `Node Value Last Tier(leaves) -> F`
- `Order Leaves By Key({(Key, Value)}) -> {(Key, Value})`

## Known blockers

These implementations will require new VM instructions and/or advice provider modification:

- `H_{t}({F}) -> F`

Hash in domain is currently not supported as VM instruction

- `Insert Leaf(Root, N, depth, index, Key, Value) -> New Root: F`

We can map `(depth, index) -> (Key, Value)` via the advice provider, but we cannot insert a leaf on an arbitrary index.

## Nice to have

The advice provider will allow us to map values to sequence of values. This theoretically can solve any situation, but might be too resource demanding to work with. Example:

If I'm to implement the `Node(state, depth, index) -> Node Value: F`, then I can do the following:

- Compute the hash of the arguments `x := H(state, depth, index)`
- Map `x -> v`

This means we will have to store every node, not only as a node, but also as a value mapping.

If we have a way to perform a custom request that will take `n` numbers as argument, we can easily implement more functions:

- Define a constant `N` that will work as function selector
- Invoke the advice provider, passing as arguments `(N, state, depth, index)`
- Given `N`, the advice provider will know it should use the 3 arguments to fetch the node for the given state at depth+index, and return it

**Comment by vlopes11** [comment]
Following the proposal of a common merkle store backend, the described routines are feasible with such backend

https://github.com/0xPolygonMiden/crypto/issues/89#issuecomment-1460756669

| TSMT Requirement | Implementation |
| --- | --- |
| `H_0(depth) -> F` | [EmptySubtreeRoots::empty_hashes(depth)[depth]](https://github.com/0xPolygonMiden/crypto/blob/2871e4eb27be074f2cc80881342d0bb6d15929f8/src/merkle/empty_roots.rs#L17-L24) |
| `H_{t}({F}) -> F` | . |
| `Node(state, depth, index) -> Node Value: F` | . |
| `Traverse(state, bits) -> Target Node Depth Index: (F, F)` | . |
| `Fetch Pre Image(Root, depth, index) -> {F}` | . |
| `Insert Leaf(Root, N, depth, index, Key, Value) -> New Root: F` | . |
| `Last Tier Leaves(index) -> {(Key, Value)}` | . |
| `Merkle Opening(Root, V, index, Merkle Path) -> boolean` | . |
| `Merkle Path(Root, depth, index) -> Merkle Path` | . |
| `Node Value Last Tier(leaves) -> F` | . |
| `Order Leaves By Key({(Key, Value)}) -> {(Key, Value})` | . |

**Comment by bobbinth** [comment]
I think we should view this from the standpoint of having access to the `AdvcieProvider`. So, for example:

`Fetch Pre Image(root, depth, index)` could be done as follows:
- `AdviceProvider::get_tree_node(root, (depth, index)) -> node`
- `AdviceProvider::write_tape(source: node)`
- `AdvcieProvider::read_tape_dw() -> pre_image`

**Comment by bobbinth** [comment]
Closing this as superseded by #152 and others.
